security:
    encoders:
        App\Entity\User:
            algorithm: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: firstname
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
#            provider: app_user_provider


    access_control:
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        # - { path: ^/profile, roles: ROLE_USER }
