security:
    encoders:
        App\Entity\User:
            algorithm: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure


        refresh:
            pattern: ^/api/token/refresh
            stateless: true
            anonymous: true

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

            form_login:
                login_path: app_login
                check_path: app_login
                provider: app_user_provider

            logout:
                path: app_logout
                target: /login


    access_control:
#         - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/api/courses, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#         - { path: ^/users, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/courses, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/delete, roles: IS_AUTHENTICATED_FULLY }
         - { path: ^/edit, roles: IS_AUTHENTICATED_FULLY }
